pipeline {
    agent any
    options {
        timeout(time: 30, unit: 'MINUTES')
    }
    stages {
        stage('Build') {
            steps {
                echo '########### Commiter ${GIT_COMMITTER_NAME} ###########'
                echo 'building branch ${GIT_BRANCH}..'
                sh 'mvn -V clean compile'
            }
        }
        stage('Unit Tests') {
            steps {
                echo 'running unit tests..'
                sh 'mvn -V test'
            }
        }

        stage('Integration Tests') {
            steps {
                echo 'running integration tests..'
                sh 'mvn -V failsafe:integration-test'
            }
        }

    }
}